name: Test Trigger

on:
  push:
    branches:
      - main
      - szczys/ci-gateway
  pull_request:
  workflow_dispatch:

jobs:
  test-integration:
    name: pouch-integration-tests
    uses: ./.github/workflows/test-integration.yml
    secrets: inherit

    strategy:
      matrix:
        manifest_yml:
          - west
          - west-ncs
      fail-fast: false

    with:
      manifest_yml: ${{ matrix.manifest_yml }}


  test-hil:
    name: pouch-tests
    uses: ./.github/workflows/test-hil.yml
    secrets: inherit

    strategy:
      fail-fast: false
      matrix:
        include:
          - hil_board: nrf52840dk
            west_board: nrf52840dk/nrf52840
            manifest_yml: west
            binary_file: zephyr.signed.hex
          - hil_board: nrf52840dk
            west_board: nrf52840dk/nrf52840
            manifest_yml: west-ncs
            binary_file: merged.hex
            run_hil_test: true

    with:
      hil_board: ${{ matrix.hil_board }}
      west_board: ${{ matrix.west_board }}
      manifest_yml: ${{ matrix.manifest_yml }}
      binary_file: ${{ matrix.binary_file}}
      binary_blob: ${{ matrix.binary_blob }}
      run_hil_test: ${{ matrix.run_hil_test || false }}
      gw_board: frdm_rw612
      gw_version: f30be4530c17ce8543833c8bb3172f8e1b4510ff
      gw_manifest_yml: west-zephyr
      gw_blobs: hal_nxp
