name: Test Trigger

on:
  push:
    branches:
      - main
      - dnm/test-suite-names
  pull_request:
  workflow_dispatch:

jobs:
  test-integration:
    name: pouch-integration-tests
    uses: ./.github/workflows/test-integration.yml
    secrets: inherit

    strategy:
      matrix:
        manifest_yml:
          - west
          - west-ncs
      fail-fast: false

    with:
      manifest_yml: ${{ matrix.manifest_yml }}


  publish-test-summaries:
    if: success() || failure()
    needs:
      - test-integration
    runs-on: ubuntu-24.04
    steps:
      - name: Gather summaries
        uses: actions/download-artifact@v4
        with:
          path: summary
          pattern: ci-summary-*
          merge-multiple: true

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: summary/*.xml
          detailed_summary: true
          group_suite: true
